/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;

/**
 *
 * @author saidn
 */
public class Batallas extends javax.swing.JFrame {

    private Cuentas sistemaCuentas;
    private Usuario usuarioActual;

    public Batallas() {
        initComponents();

        displayHeroStatistics();
        displayVillainStatistics();
    }

    public Batallas(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750, 920);
        this.setLocationRelativeTo(null);
        displayHeroStatistics();
        displayVillainStatistics();
    }

    private void displayVillainStatistics() {
        StringBuilder villainStats = new StringBuilder();
        villainStats.append("Estadísticas de Villanos:\n\n");
        villainStats.append("Victorias Totales de Villanos: ").append(Cuentas.getTotalVictoriasVillanos()).append("\n");

        jTextArea1.setText(villainStats.toString());
        jTextArea1.setEditable(false);
    }

    private void displayHeroStatistics() {
        StringBuilder heroStats = new StringBuilder();
        heroStats.append("Estadísticas de Héroes:\n\n");
        heroStats.append("Victorias Totales de Héroes: ").append(Cuentas.getTotalVictoriasHeroes()).append("\n");

        jTextArea2.setText(heroStats.toString());
        jTextArea2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tituloVillanos = new javax.swing.JLabel();
        tituloHeroes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Batallas Mundiales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 140, 380, 170);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 310, 238, 440);

        regresar.setBackground(new java.awt.Color(102, 102, 0));
        regresar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(230, 830, 290, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 300, 238, 440);

        tituloVillanos.setBackground(new java.awt.Color(102, 102, 0));
        tituloVillanos.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tituloVillanos.setForeground(new java.awt.Color(0, 0, 0));
        tituloVillanos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVillanos.setText("Villanos");
        tituloVillanos.setOpaque(true);
        getContentPane().add(tituloVillanos);
        tituloVillanos.setBounds(500, 280, 100, 14);

        tituloHeroes.setBackground(new java.awt.Color(102, 102, 0));
        tituloHeroes.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tituloHeroes.setForeground(new java.awt.Color(0, 0, 0));
        tituloHeroes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHeroes.setText("Heroes");
        tituloHeroes.setOpaque(true);
        getContentPane().add(tituloHeroes);
        tituloHeroes.setBounds(150, 280, 100, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        new UniversoMarvel(sistemaCuentas, usuarioActual).setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel tituloHeroes;
    private javax.swing.JLabel tituloVillanos;
    // End of variables declaration//GEN-END:variables
}
