/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class cambiarContras extends javax.swing.JFrame {

    private Cuentas sistemaCuentas;
    private Usuario usuarioActual;

    public cambiarContras(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750,920);
        this.setLocationRelativeTo(null);
        this.setTitle("Cambiar Contraseña");
        registraru.setText(usuario.getUsuario());
        registraru.setEditable(false);
    }
    
    public cambiarContras() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        confcontra = new javax.swing.JLabel();
        labelu = new javax.swing.JLabel();
        labelcontra = new javax.swing.JLabel();
        botonCambiar = new javax.swing.JButton();
        registrarc = new javax.swing.JTextField();
        registraru = new javax.swing.JTextField();
        textconf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresar.setBackground(new java.awt.Color(102, 102, 0));
        regresar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(280, 720, 210, 50);

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiar Contraseña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 190, 380, 170);

        confcontra.setBackground(new java.awt.Color(102, 102, 0));
        confcontra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        confcontra.setForeground(new java.awt.Color(0, 0, 0));
        confcontra.setText("Confirmar Contraseña:");
        confcontra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        confcontra.setOpaque(true);
        getContentPane().add(confcontra);
        confcontra.setBounds(100, 560, 260, 50);

        labelu.setBackground(new java.awt.Color(102, 102, 0));
        labelu.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        labelu.setForeground(new java.awt.Color(0, 0, 0));
        labelu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        labelu.setText("Usuario:");
        labelu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        labelu.setOpaque(true);
        getContentPane().add(labelu);
        labelu.setBounds(100, 410, 260, 50);

        labelcontra.setBackground(new java.awt.Color(102, 102, 0));
        labelcontra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        labelcontra.setForeground(new java.awt.Color(0, 0, 0));
        labelcontra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        labelcontra.setText("Contraseña:");
        labelcontra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        labelcontra.setOpaque(true);
        getContentPane().add(labelcontra);
        labelcontra.setBounds(100, 490, 260, 50);

        botonCambiar.setBackground(new java.awt.Color(102, 102, 0));
        botonCambiar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        botonCambiar.setForeground(new java.awt.Color(0, 0, 0));
        botonCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-registro-24.png"))); // NOI18N
        botonCambiar.setText("cambiar contraseña");
        botonCambiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCambiarMouseClicked(evt);
            }
        });
        getContentPane().add(botonCambiar);
        botonCambiar.setBounds(280, 650, 210, 50);

        registrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarcActionPerformed(evt);
            }
        });
        getContentPane().add(registrarc);
        registrarc.setBounds(390, 490, 270, 50);

        registraru.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                registraruComponentAdded(evt);
            }
        });
        registraru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraruActionPerformed(evt);
            }
        });
        getContentPane().add(registraru);
        registraru.setBounds(390, 410, 270, 50);

        textconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textconfActionPerformed(evt);
            }
        });
        getContentPane().add(textconf);
        textconf.setBounds(390, 560, 270, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCambiarMouseClicked
        String currentPassword = JOptionPane.showInputDialog(this, 
            "Para continuar, ingrese su contraseña ACTUAL:", 
            "Verificación de Seguridad", JOptionPane.QUESTION_MESSAGE);
        
        if (currentPassword == null) {
            return; // El usuario presionó cancelar
        }

        if (!usuarioActual.confirmarcontra(currentPassword.trim())) { //
            JOptionPane.showMessageDialog(this, "Contraseña actual incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nuevaContra = registrarc.getText();
        String confContra = textconf.getText();

        if (nuevaContra.trim().isEmpty() || confContra.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos de nueva contraseña no pueden estar vacíos.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (nuevaContra.length() != 5) {
            JOptionPane.showMessageDialog(this, "La nueva contraseña debe tener exactamente 5 caracteres.", "Longitud Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!nuevaContra.equals(confContra)) {
            JOptionPane.showMessageDialog(this, "Las nuevas contraseñas no coinciden.", "Error de Confirmación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- CÓDIGO NUEVO: Mensaje de confirmación ---
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea cambiar su contraseña?", 
            "Confirmar Cambio", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean cambioExitoso = sistemaCuentas.cambiarcontra(usuarioActual.getUsuario(), currentPassword.trim(), nuevaContra); //
            
            if (cambioExitoso) {
                JOptionPane.showMessageDialog(this, "¡Contraseña cambiada exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                // Navega directamente al menú de perfil
                new MiPerfilMenu(sistemaCuentas, usuarioActual).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al cambiar la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_botonCambiarMouseClicked

    private void registrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarcActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registrarcActionPerformed

    private void registraruComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_registraruComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_registraruComponentAdded

    private void registraruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registraruActionPerformed

    private void textconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textconfActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
new MiPerfilMenu(sistemaCuentas, usuarioActual).setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambiar;
    private javax.swing.JLabel confcontra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelcontra;
    private javax.swing.JLabel labelu;
    private javax.swing.JTextField registrarc;
    private javax.swing.JTextField registraru;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField textconf;
    // End of variables declaration//GEN-END:variables
}
