/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class eliminarCuenta extends javax.swing.JFrame {

    private Cuentas sistemaCuentas;
    private Usuario usuarioActual;

    public eliminarCuenta(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750,920);
        this.setLocationRelativeTo(null);
        labelcontra.setText("Ingrese Contraseña:");
        confcontra.setVisible(false); // No necesitamos confirmar dos veces
        textconf.setVisible(false);   // Ocultamos el campo extra
        registraru.setText(usuario.getUsuario()); // Mostramos el usuario a eliminar
        registraru.setEditable(false);
    }
    
    public eliminarCuenta() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        confcontra = new javax.swing.JLabel();
        labelu = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        registrarc = new javax.swing.JTextField();
        labelcontra = new javax.swing.JLabel();
        registraru = new javax.swing.JTextField();
        textconf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresar.setBackground(new java.awt.Color(102, 102, 0));
        regresar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(290, 760, 210, 50);

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Cuenta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 230, 380, 170);

        confcontra.setBackground(new java.awt.Color(102, 102, 0));
        confcontra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        confcontra.setForeground(new java.awt.Color(0, 0, 0));
        confcontra.setText("Confirmar Contraseña:");
        confcontra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        confcontra.setOpaque(true);
        getContentPane().add(confcontra);
        confcontra.setBounds(110, 610, 260, 50);

        labelu.setBackground(new java.awt.Color(102, 102, 0));
        labelu.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        labelu.setForeground(new java.awt.Color(0, 0, 0));
        labelu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        labelu.setText("Usuario:");
        labelu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        labelu.setOpaque(true);
        getContentPane().add(labelu);
        labelu.setBounds(110, 460, 260, 50);

        confirmar.setBackground(new java.awt.Color(102, 102, 0));
        confirmar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        confirmar.setForeground(new java.awt.Color(0, 0, 0));
        confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-registro-24.png"))); // NOI18N
        confirmar.setText("confirmar");
        confirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(290, 700, 210, 50);

        registrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarcActionPerformed(evt);
            }
        });
        getContentPane().add(registrarc);
        registrarc.setBounds(400, 540, 270, 50);

        labelcontra.setBackground(new java.awt.Color(102, 102, 0));
        labelcontra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        labelcontra.setForeground(new java.awt.Color(0, 0, 0));
        labelcontra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-maravilla-48.png"))); // NOI18N
        labelcontra.setText("Contraseña:");
        labelcontra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        labelcontra.setOpaque(true);
        getContentPane().add(labelcontra);
        labelcontra.setBounds(110, 540, 260, 50);

        registraru.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                registraruComponentAdded(evt);
            }
        });
        registraru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraruActionPerformed(evt);
            }
        });
        getContentPane().add(registraru);
        registraru.setBounds(400, 460, 270, 50);

        textconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textconfActionPerformed(evt);
            }
        });
        getContentPane().add(textconf);
        textconf.setBounds(400, 610, 270, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed

      int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está SEGURO de que desea ELIMINAR su cuenta?\nEsta acción no se puede deshacer.", 
            "CONFIRMACIÓN FINAL", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        String password = registrarc.getText();
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar su contraseña para confirmar.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean resultado = sistemaCuentas.eliminarUsuario(usuarioActual.getUsuario(), password.trim());
        
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Su cuenta ha sido eliminada.", "Cuenta Eliminada", JOptionPane.INFORMATION_MESSAGE);
            new Proyecto2_1(sistemaCuentas).setVisible(true); // Regresa al menú de login inicial
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta. La eliminación ha sido cancelada.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_confirmarActionPerformed

    private void registrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarcActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registrarcActionPerformed

    private void registraruComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_registraruComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_registraruComponentAdded

    private void registraruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registraruActionPerformed

    private void textconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textconfActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
new MiPerfilMenu(sistemaCuentas, usuarioActual).setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confcontra;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelcontra;
    private javax.swing.JLabel labelu;
    private javax.swing.JTextField registrarc;
    private javax.swing.JTextField registraru;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField textconf;
    // End of variables declaration//GEN-END:variables
}
