/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;

public class MiPerfilMenu extends javax.swing.JFrame {

    private Cuentas sistemaCuentas;
    private Usuario usuarioActual;

    public MiPerfilMenu(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750,920);
        this.setLocationRelativeTo(null);
        setTitle("Menú de Perfil de " + usuario.getUsuario());
    }
    
    public MiPerfilMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cambiarContra1 = new javax.swing.JButton();
        logJuegos = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        cambiarContra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Universo Marvel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(102, 102, 0));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menu de Perfil");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 210, 380, 170);

        cambiarContra1.setBackground(new java.awt.Color(102, 102, 0));
        cambiarContra1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        cambiarContra1.setForeground(new java.awt.Color(0, 0, 0));
        cambiarContra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ajustes-48.png"))); // NOI18N
        cambiarContra1.setText("Cambiar contraseña");
        cambiarContra1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cambiarContra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContra1ActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarContra1);
        cambiarContra1.setBounds(250, 500, 240, 70);

        logJuegos.setBackground(new java.awt.Color(102, 102, 0));
        logJuegos.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        logJuegos.setForeground(new java.awt.Color(0, 0, 0));
        logJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-masculino-en-círculo-48.png"))); // NOI18N
        logJuegos.setText("historial de partidas");
        logJuegos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(logJuegos);
        logJuegos.setBounds(250, 410, 240, 70);

        regresar.setBackground(new java.awt.Color(102, 102, 0));
        regresar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        regresar.setText("regresar");
        regresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(250, 680, 240, 70);

        cambiarContra.setBackground(new java.awt.Color(102, 102, 0));
        cambiarContra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        cambiarContra.setForeground(new java.awt.Color(0, 0, 0));
        cambiarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ajustes-48.png"))); // NOI18N
        cambiarContra.setText("eliminar cuenta");
        cambiarContra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarContra);
        cambiarContra.setBounds(250, 590, 240, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logJuegosActionPerformed
        new historialPartidas(sistemaCuentas, usuarioActual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logJuegosActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
       new Juego(sistemaCuentas, usuarioActual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void cambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraActionPerformed
       new eliminarCuenta(sistemaCuentas, usuarioActual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarContraActionPerformed

    private void cambiarContra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContra1ActionPerformed
       new cambiarContras(sistemaCuentas, usuarioActual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarContra1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContra;
    private javax.swing.JButton cambiarContra1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logJuegos;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
