/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import Logica.Cuentas;
import Logica.Usuario;

public class Ranking extends javax.swing.JFrame {

     private Cuentas sistemaCuentas;
    private Usuario usuarioActual;
    
    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        
    }
    
    public Ranking(Cuentas sistema, Usuario usuario) {
        this.sistemaCuentas = sistema;
        this.usuarioActual = usuario;
        initComponents();
        setSize(750,920);
        this.setLocationRelativeTo(null);
        tituloVillanos.setText("RANKING MUNDIAL");
        tituloVillanos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVillanos.setBounds(80, 250, 590, 20);

        jScrollPane1.setBounds(80, 280, 590, 460);

        displayRanking();
    }
    
private void displayRanking() {
        Usuario[] usuarios = sistemaCuentas.getUsuarios(); //
        int n = sistemaCuentas.getNumUsuarios();

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (usuarios[j].getPuntaje() < usuarios[j + 1].getPuntaje()) { //
                    Usuario temp = usuarios[j];
                    usuarios[j] = usuarios[j + 1];
                    usuarios[j + 1] = temp;
                }
            }
        }

        StringBuilder sb = new StringBuilder();

        if (n == 0) {
            sb.append("No hay jugadores registrados.");
        } else {
            for (int i = 0; i < n; i++) {
                Usuario usuario = usuarios[i];
                String linea = String.format("%d. %-20s - Puntos: %d\n", 
                                             (i + 1), 
                                             usuario.getUsuario(), 
                                             usuario.getPuntaje());
                sb.append(linea);
            }
        }
        
        jTextArea1.setText(sb.toString());
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 16)); 
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tituloVillanos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        regresar.setBackground(new java.awt.Color(102, 102, 0));
        regresar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        regresar.setForeground(new java.awt.Color(0, 0, 0));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(230, 830, 290, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(78, 300, 590, 440);

        tituloVillanos.setBackground(new java.awt.Color(102, 102, 0));
        tituloVillanos.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        tituloVillanos.setForeground(new java.awt.Color(0, 0, 0));
        tituloVillanos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVillanos.setText("LeaderBoard");
        tituloVillanos.setOpaque(true);
        getContentPane().add(tituloVillanos);
        tituloVillanos.setBounds(210, 150, 330, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk4.jpg"))); // NOI18N
        jLabel2.setText("Eliminar Cuenta");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        new UniversoMarvel(sistemaCuentas, usuarioActual).setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel tituloVillanos;
    // End of variables declaration//GEN-END:variables
}
